name: friendo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.2.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.2.1+1
  hexcolor: ^3.0.1
  shared_preferences: ^2.0.17
  image_picker: ^0.8.9
  cached_network_image: ^3.1.0
  logging: ^1.2.0
  sqflite: ^2.2.8+4
  http: ^1.1.0
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  cloud_firestore: ^4.7.0
  firebase_storage: ^11.2.3
  firebase_messaging: ^14.6.4
  curved_labeled_navigation_bar: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
  
  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
